name: ccid
description: "A Flutter plugin for smart card reader using CCID protocol."
version: 0.1.0
homepage: https://github.com/nfcim/ccid

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  dart_pcsc: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  platform_detector: ^0.2.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: im.nfc.ccid
        pluginClass: CcidPlugin
      ios:
        pluginClass: CcidPlugin
      linux:
        pluginClass: CcidPlugin
      macos:
        pluginClass: CcidPlugin
      windows:
        pluginClass: CcidPluginCApi
