name: ccid
description: "A Flutter plugin for smart card reader using CCID protocol with PC/SC-like APIs."
version: 0.1.5
homepage: https://github.com/nfcim/ccid

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  dart_pcsc: ^2.0.2
  plugin_platform_interface: ^2.1.8
  platform_detector: ^0.2.0
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: im.nfc.ccid
        pluginClass: CcidPlugin
      ios:
        pluginClass: CcidPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: CcidPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: CcidPlugin
      windows:
        pluginClass: CcidPluginCApi
