name: Build Example App

on: [push, pull_request]

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    strategy:
      fail-fast: false
      matrix:
        target: [android, linux, windows, macos]
        include:
          - target: android
            os: ubuntu-latest
            build-command: flutter build apk --debug --verbose
            artifact-path: build/app/outputs/apk/debug/app-debug.apk
            pre-build: ""
          - target: linux
            os: ubuntu-latest
            build-command: flutter build linux --verbose
            artifact-path: build/linux/x64/debug/bundle
            pre-build: |
              sudo apt-get update -y
              sudo apt-get install -y ninja-build libgtk-3-dev
          - target: windows
            os: windows-latest
            build-command: flutter build windows --debug --verbose
            artifact-path: build/windows/runner
            pre-build: ""
          - target: macos
            os: macos-latest
            build-command: flutter build macos --debug --verbose
            artifact-path: build/macos/Build/Products/Debug/Runner.app
            pre-build: ""

    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      if: ${{ matrix.target == 'android' }}
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - name: Pre-build script for ${{ matrix.target }}
      run: ${{ matrix.pre-build }}
    - run: dart pub get
    - run: dart format --output=none --set-exit-if-changed .
    - run: dart analyze
    - run: flutter pub get
      working-directory: example/
    - name: Run flutter build on ${{ matrix.target }}
      run: ${{ matrix.build-command }}
      working-directory: example/
    - uses: actions/upload-artifact@v4
      with:
        name: example-${{ matrix.target }}-debug
        path: ${{ matrix.artifact-path }}
